/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CalculatorStandart;

/**
 *
 * @author Lenovo
 */
public class Calculator extends javax.swing.JFrame {
    
    Double total, input1, input2;
    int opt;
    String angka;
    int batas = 0;
    
    
    public Calculator() {
        initComponents();
        angka ="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        koma = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        min = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        esc = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        samadengan = new javax.swing.JButton();
        bs = new javax.swing.JButton();
        del = new javax.swing.JButton();
        pangkat = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        persen = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hasil = new javax.swing.JLabel();
        input = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(22, 22, 22));
        jPanel2.setLayout(null);

        b2.setBackground(new java.awt.Color(0, 0, 0));
        b2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel2.add(b2);
        b2.setBounds(90, 210, 70, 40);

        b1.setBackground(new java.awt.Color(0, 0, 0));
        b1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel2.add(b1);
        b1.setBounds(10, 210, 70, 40);

        b8.setBackground(new java.awt.Color(0, 0, 0));
        b8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        b8.setForeground(new java.awt.Color(255, 255, 255));
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel2.add(b8);
        b8.setBounds(90, 310, 70, 40);

        koma.setBackground(new java.awt.Color(51, 51, 51));
        koma.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        koma.setForeground(new java.awt.Color(255, 255, 255));
        koma.setText(".");
        koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaActionPerformed(evt);
            }
        });
        jPanel2.add(koma);
        koma.setBounds(170, 360, 70, 40);

        b3.setBackground(new java.awt.Color(0, 0, 0));
        b3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel2.add(b3);
        b3.setBounds(170, 210, 70, 40);

        min.setBackground(new java.awt.Color(51, 51, 51));
        min.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        min.setForeground(new java.awt.Color(255, 255, 255));
        min.setText("-");
        min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minActionPerformed(evt);
            }
        });
        jPanel2.add(min);
        min.setBounds(250, 210, 70, 40);

        b4.setBackground(new java.awt.Color(0, 0, 0));
        b4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 255, 255));
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel2.add(b4);
        b4.setBounds(10, 260, 70, 40);

        b5.setBackground(new java.awt.Color(0, 0, 0));
        b5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        b5.setForeground(new java.awt.Color(255, 255, 255));
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel2.add(b5);
        b5.setBounds(90, 260, 70, 40);

        b6.setBackground(new java.awt.Color(0, 0, 0));
        b6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        b6.setForeground(new java.awt.Color(255, 255, 255));
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel2.add(b6);
        b6.setBounds(170, 260, 70, 40);

        kali.setBackground(new java.awt.Color(51, 51, 51));
        kali.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        kali.setForeground(new java.awt.Color(255, 255, 255));
        kali.setText("x");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        jPanel2.add(kali);
        kali.setBounds(250, 260, 70, 40);

        bagi.setBackground(new java.awt.Color(51, 51, 51));
        bagi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bagi.setForeground(new java.awt.Color(255, 255, 255));
        bagi.setText("/");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        jPanel2.add(bagi);
        bagi.setBounds(250, 310, 70, 40);

        b9.setBackground(new java.awt.Color(0, 0, 0));
        b9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        b9.setForeground(new java.awt.Color(255, 255, 255));
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel2.add(b9);
        b9.setBounds(170, 310, 70, 40);

        b7.setBackground(new java.awt.Color(0, 0, 0));
        b7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        b7.setForeground(new java.awt.Color(255, 255, 255));
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel2.add(b7);
        b7.setBounds(10, 310, 70, 40);

        esc.setBackground(new java.awt.Color(58, 58, 58));
        esc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        esc.setForeground(new java.awt.Color(255, 255, 255));
        esc.setText("<---");
        esc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escActionPerformed(evt);
            }
        });
        jPanel2.add(esc);
        esc.setBounds(10, 360, 70, 40);

        b0.setBackground(new java.awt.Color(0, 0, 0));
        b0.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        b0.setForeground(new java.awt.Color(255, 255, 255));
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        jPanel2.add(b0);
        b0.setBounds(90, 360, 70, 40);

        samadengan.setBackground(new java.awt.Color(51, 51, 51));
        samadengan.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        samadengan.setForeground(new java.awt.Color(255, 255, 255));
        samadengan.setText("=");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });
        jPanel2.add(samadengan);
        samadengan.setBounds(250, 360, 70, 40);

        bs.setBackground(new java.awt.Color(51, 51, 51));
        bs.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bs.setForeground(new java.awt.Color(255, 255, 255));
        bs.setText("C");
        bs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsActionPerformed(evt);
            }
        });
        jPanel2.add(bs);
        bs.setBounds(10, 160, 70, 40);

        del.setBackground(new java.awt.Color(51, 51, 51));
        del.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        del.setForeground(new java.awt.Color(255, 255, 255));
        del.setText("CE");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel2.add(del);
        del.setBounds(90, 160, 70, 40);

        pangkat.setBackground(new java.awt.Color(51, 51, 51));
        pangkat.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pangkat.setForeground(new java.awt.Color(255, 255, 255));
        pangkat.setText("^");
        pangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pangkatActionPerformed(evt);
            }
        });
        jPanel2.add(pangkat);
        pangkat.setBounds(170, 160, 70, 40);

        plus.setBackground(new java.awt.Color(51, 51, 51));
        plus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        plus.setForeground(new java.awt.Color(255, 255, 255));
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        jPanel2.add(plus);
        plus.setBounds(250, 160, 70, 40);

        sin.setBackground(new java.awt.Color(51, 51, 51));
        sin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sin.setForeground(new java.awt.Color(255, 255, 255));
        sin.setText("sin");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });
        jPanel2.add(sin);
        sin.setBounds(90, 110, 70, 40);

        cos.setBackground(new java.awt.Color(51, 51, 51));
        cos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cos.setForeground(new java.awt.Color(255, 255, 255));
        cos.setText("cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });
        jPanel2.add(cos);
        cos.setBounds(170, 110, 70, 40);

        tan.setBackground(new java.awt.Color(51, 51, 51));
        tan.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tan.setForeground(new java.awt.Color(255, 255, 255));
        tan.setText("tan");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });
        jPanel2.add(tan);
        tan.setBounds(250, 110, 70, 40);

        persen.setBackground(new java.awt.Color(51, 51, 51));
        persen.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        persen.setForeground(new java.awt.Color(255, 255, 255));
        persen.setText("%");
        persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenActionPerformed(evt);
            }
        });
        jPanel2.add(persen);
        persen.setBounds(10, 110, 70, 40);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setText("-");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(38, 275, 20, 20);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("+");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(37, 260, 20, 30);

        hasil.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        hasil.setForeground(new java.awt.Color(147, 147, 147));
        hasil.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(hasil);
        hasil.setBounds(10, 10, 310, 30);

        input.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        input.setForeground(new java.awt.Color(255, 255, 255));
        input.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        input.setText("0");
        jPanel2.add(input);
        input.setBounds(10, 60, 310, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 330, 420);

        setSize(new java.awt.Dimension(341, 455));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed

 angka +="0";
 input.setText(angka);

    }//GEN-LAST:event_b0ActionPerformed

    private void komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaActionPerformed
angka += ".";
input.setText(angka);
    }//GEN-LAST:event_komaActionPerformed

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed
    input2=Double.parseDouble(angka);
   
    if (opt==1){
       total = input1+input2;
       angka = Double.toString(total);
       input.setText(angka);
       hasil.setText(input1+" + "+input2);
    }    
    else if(opt==2){
        total = input1-input2;
        angka = Double.toString(total);
        input.setText(angka);
        hasil.setText(input1+" - "+input2);        
    }
    else if(opt==3){
        total = input1 * input2;
        angka = Double.toString(total);
        input.setText(angka);
        hasil.setText(input1+" x "+input2);
    }
    else if(opt==4){
        total = input1 / input2;
        angka = Double.toString(total);
        input.setText(angka);
        hasil.setText(input1+" / "+input2);
    }
    else if(opt==5){
        total = Math.pow(input1, input2);
        angka = Double.toString(total);
        input.setText(angka);
        hasil.setText(input1+" ^ "+input2);
    }
    batas = 1;
    }//GEN-LAST:event_samadenganActionPerformed

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
input1=Double.parseDouble(angka);
hasil.setText(angka+" -");
input.setText("");
angka ="";
opt=2;
    }//GEN-LAST:event_minActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
if(batas==1){ 
 input.setText("");
 hasil.setText("");
 angka="";
 angka += "9";
 input.setText(angka);
 batas=0;
}
else if(batas==0){
 angka +="9";
 input.setText(angka);
}
    }//GEN-LAST:event_b9ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
if(batas==1){ 
 input.setText("");
 hasil.setText("");
 angka="";
 angka += "8";
 input.setText(angka);
 batas=0;
}
else if(batas==0){
 angka +="8";
 input.setText(angka);
}
    }//GEN-LAST:event_b8ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
if(batas==1){ 
 input.setText("");
 hasil.setText("");
 angka="";
 angka += "7";
 input.setText(angka);
 batas=0;
}
else if(batas==0){
 angka +="7";
 input.setText(angka);
}
    }//GEN-LAST:event_b7ActionPerformed

    private void escActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escActionPerformed
angka=angka.substring(0,angka.length()-1);
input.setText(angka);
    }//GEN-LAST:event_escActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
if(batas==1){ 
 input.setText("");
 hasil.setText("");
 angka="";
 angka += "6";
 input.setText(angka);
 batas=0;
}
else if(batas==0){
 angka +="6";
 input.setText(angka);
}
    }//GEN-LAST:event_b6ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
if(batas==1){ 
 input.setText("");
 hasil.setText("");
 angka="";
 angka += "5";
 input.setText(angka);
 batas=0;
}
else if(batas==0){
 angka +="5";
 input.setText(angka);
}
    }//GEN-LAST:event_b5ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
if(batas==1){ 
 input.setText("");
 hasil.setText("");
 angka="";
 angka += "4";
 input.setText(angka);
 batas=0;
}
else if(batas==0){
 angka +="4";
 input.setText(angka);
}
    }//GEN-LAST:event_b4ActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
input1=Double.parseDouble(angka);
hasil.setText(angka+" /");
input.setText("");
angka ="";
opt=4;
    }//GEN-LAST:event_bagiActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
if(batas==1){ 
 input.setText("");
 hasil.setText("");
 angka="";
 angka += "3";
 input.setText(angka);
 batas=0;
}
else if(batas==0){
 angka +="3";
 input.setText(angka);
}
    }//GEN-LAST:event_b3ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
if(batas==1){ 
 input.setText("");
 hasil.setText("");
 angka="";
 angka += "2";
 input.setText(angka);
 batas=0;
}
else if(batas==0){
 angka +="2";
 input.setText(angka);
}
    }//GEN-LAST:event_b2ActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
input1=Double.parseDouble(angka);
hasil.setText(angka+" x");
input.setText("");
angka ="";
opt=3;
    }//GEN-LAST:event_kaliActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
if(batas==1){
input.setText(""); 
hasil.setText("");
angka = "";
angka += "1";
input.setText(angka);
batas=0;
}
else if(batas==0){
angka += "1";
input.setText(angka);
}
    }//GEN-LAST:event_b1ActionPerformed

    private void bsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsActionPerformed
  input.setText("0");
 hasil.setText("");
 angka = "";
    }//GEN-LAST:event_bsActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
input.setText("0");
 angka = "";
    }//GEN-LAST:event_delActionPerformed

    private void pangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pangkatActionPerformed
input1=Double.parseDouble(angka);
hasil.setText(""+angka+" ^");
input.setText("");
angka="";
opt=5;
    }//GEN-LAST:event_pangkatActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
input1=Double.parseDouble(angka);
hasil.setText(""+angka+" +");
input.setText("");
angka="";
opt=1;
    }//GEN-LAST:event_plusActionPerformed

    private void persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenActionPerformed
input1=Double.parseDouble(angka);
hasil.setText(""+angka+" %");
total=input1/100;
input.setText(""+total);
angka="";
    }//GEN-LAST:event_persenActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
input1=Double.parseDouble(angka);
hasil.setText("sin "+angka);
total=Math.sin(input1);
input.setText(""+total);
angka="";
    }//GEN-LAST:event_sinActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
input1=Double.parseDouble(angka);
hasil.setText("cos "+angka);
total=Math.cos(input1);
input.setText(""+total);
angka="";
    }//GEN-LAST:event_cosActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
input1=Double.parseDouble(angka);
hasil.setText("tan "+angka);
total=Math.tan(input1);
input.setText(""+total);
angka="";

    }//GEN-LAST:event_tanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bagi;
    private javax.swing.JButton bs;
    private javax.swing.JButton cos;
    private javax.swing.JButton del;
    private javax.swing.JButton esc;
    private javax.swing.JLabel hasil;
    private javax.swing.JLabel input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kali;
    private javax.swing.JButton koma;
    private javax.swing.JButton min;
    private javax.swing.JButton pangkat;
    private javax.swing.JButton persen;
    private javax.swing.JButton plus;
    private javax.swing.JButton samadengan;
    private javax.swing.JButton sin;
    private javax.swing.JButton tan;
    // End of variables declaration//GEN-END:variables
}
